---
title: "R Notebook"
output:
pdf_document: default
html_notebook: default
---

```{r}
library(itsmr)
```

# Test ITSMR Package
```{r}
#### Test itsmr package ####
plot(wine,type='l')
plot(deaths,type='l')
plot(uspop,type='l')
plot(strikes,type='l')
```

# Example 1.3.4 

```{r}

# Plot of US population and trend (polynomial order 2)
y <- trend(uspop,2)
plotc(uspop,y)
```

# Example 1.3.5

```{r}
# Plot of Lake Huron water levels
y <- trend(lake,1)
par(mfrow=c(2,1))
plotc(lake,y)
title('Lake Huron Data')
plotc(lake-y,rep(0,length(lake)))
title('Residuals')
par(mfrow=c(1,1))
```

# Example 1.3.6
```{r}

# Example of Harmonic Regression
y = hr(deaths,c(12,6))
plotc(deaths,y)
```

# Example 1.4.6
```{r}

# noise
set.seed(1)
y <- rnorm(200, mean = 0, sd = 1)
par(mfrow=c(2,1))
plot(y,type='l')
title('Randomly Generated Noise')
sample_variance <- acvf(y,0)

# note divide by sample variance to get autocorrelation
plot(acvf(y,40)/sample_variance,type='h')
title('Sample Autocorrelation')

# wine data
plot(wine,type='l')
title('Wine Data')
sample_variance <- acvf(wine,0)

# note divide by sample variance to get autocorrelation
plot(acvf(wine,40)/sample_variance,type='h')
title('Sample Autocorrelation')
```

# Example 1.5.1
```{r}
par(mfrow=c(1,3))
plotc(strikes,smooth.ma(strikes,2))
title('MA Smooth')
plotc(strikes,smooth.exp(strikes,.4))
title('Exp Smooth')
plotc(strikes,smooth.fft(strikes,.4))
title('FFT Smooth')

```

# Example 1.5.3
```{r}
par(mfrow=c(2,1))
plot(diff(uspop),type='o')
title('First Differences')
plot(diff(diff(uspop)),type='o')
title('Second Differences')
```

# Example 1.5.4
```{r}
par(mfrow=c(1,4))
seasonal_component <- season(deaths,12)
deseasoned <- deaths-seasonal_component
trend_component <- trend(deseasoned,2)
residuals <- deseasoned-trend_component

plot(seasonal_component,type='o')
title('Seasonal')
plot(deseasoned,type='o')
title('Deaseasoned')
plot(trend_component,type='o')
title('Trend')
plot(residuals,type='o')
title('Residuals')
```

