---
title: "Chapter 3 Exercises"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(itsmr)
```

#### Exercise 3.2

```{r}
par(mfrow=c(3,1))

# 3.1.a
arma_model = arma(Sunspots,p=2,q=1)
arma_model$phi <- c(.2,-.48)
arma_model$theta <- 1
plota(arma_model)

# 3.1.c
arma_model = arma(Sunspots,p=1,q=1)
arma_model$phi <- .6
arma_model$theta <- 1.2
plota(arma_model)
```

#### Exercise 3.9

```{r}
differenced_series <- (deaths[14:72]-deaths[13:71])-(deaths[2:60]-deaths[1:59])
sample_mean <- mean(differenced_series)
print(c('Sample Mean',sample_mean))
print('Autocorrelation')
print(acvf(differenced_series))

# Construct a sample model, using derived parameters from data (derived on paper)
z_vars <- rnorm(72,mean=0,sd=92723**.5)
y_t <- z_vars[13:72] - .585891656*z_vars[12:71] - 0.548576464*z_vars[1:60]

# Plot Random Draw of Model vs. Actual
plot(y_t,type='l')
lines(differenced_series,type='l',col='blue')
title('Model Sample (Blue) vs Actual (Black)')

```

#### Exercise 3.10

```{r}
strikes_centred <- strikes-mean(strikes)
strike_arma <- arma(strikes_centred,p=1,q=0)

# from sample AVCF and calclulations (paper) we see
# phi = .732, sigma = 560
z_vals <- rnorm(29,mean=0,sd=560)
y_t <- c(0)

for(i in 2:29){
  y_t_1 <- y_t[i-1]
  y_t <- c(y_t,.732*y_t_1+z_vals[i])
}

# Model vs. Actual
plot(strikes_centred,type='l')
lines(y_t,type='l',col='blue')
title('Model Sample (Blue) vs Actual (Black)')
```

